[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
serialize_custom_data_iii = "BuucTmJYAp3Pv1yjfHyKvGREvCqTGQTjuzjyaSiT4rkG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/m/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
